node{
	stage('SCM Checkout'){
		git 'https://github.com/hanumanad/maven'
	}
	stage('Compile-Package'){
	def mvnHome = tool name: 'maven-3.5.4', type: 'maven'
      sh "${mvnHome}/bin/mvn -f webapp/build.xml war"
        }
}
